server:
  port: 4001

spring:
  application:
    name: reception
  datasource:
    url: jdbc:h2:file:./data/reception;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  main:
    banner-mode: off

hotelos:
  broker-url: ws://localhost:4005/broker
